added REST call for customer synchronization
octopusden/octopus-oc-srv-jobs-client-provider pull request #9
Opened 2024-05-13 20:58 UTC by kriskutuzovaa

2024-05-13 21:09 UTC, kriskutuzovaa commented
@vifrrg

2024-05-14 06:09 UTC, vifrrg requested changes
Please update version and get rid of real objects and names in test data.

2024-05-14 06:09 UTC, vifrrg commented on setup.py
> +__version = "1.0.5"
Changes are enough to update `minor` component:
`1.1.0`

2024-05-14 06:09 UTC, vifrrg commented on oc_client_provider/app/client_tf.py
> +        logging.debug("Returning '%s'" % str(_result))
Please be consistent.
You used `json.dumps` previously for the same reason.

2024-05-14 06:09 UTC, vifrrg commented on oc_client_provider/app/client_tf.py
> +        :return dict: list of client data or None
This routine returns nothing actually.
Please adjust specification.

2024-05-14 06:09 UTC, vifrrg commented on oc_client_provider/app/client_tf.py
> +        :return dict: list of client data or None
This routine returns nothing actually.
Please adjust specification.

2024-05-14 06:09 UTC, vifrrg commented on oc_client_provider/app/routes.py
> +    logging.info("/sync_customer_tf")
Please add requestor's ip address to this message. You may find it in `request` object.

2024-05-14 06:09 UTC, vifrrg commented on oc_client_provider/tests/test_client_provider.py
> +        _expected_dict = list()
*IMHO*: bad idea to call a variable `dict` if it is `list` actually.

2024-05-14 06:09 UTC, vifrrg commented on oc_client_provider/tests/test_client_provider.py
> +                             json={'code': 'TEST_CLIENT_999', 'country': 'Scotland', 'language_id': 2})
Please do not use real objects (including countries) in test data.

2024-05-14 06:09 UTC, vifrrg commented on oc_client_provider/tests/test_client_provider.py
> +                                                      'country': 'Scotland', 'language_id': 2})
**Crime**: real country in test data

2024-05-14 06:09 UTC, vifrrg commented on oc_client_provider/tests/test_client_provider.py
> +        _actual_dict = response.json
`dict` variable is `list` actually

2024-05-14 06:09 UTC, vifrrg commented on oc_client_provider/tests/test_client_provider.py
> +        response = self.test_client.put("/sync_customer_tf", json={'code': 'TEST_CLIENT_999', 'country': 'Scotland'})
real country in test data

2024-05-14 06:09 UTC, vifrrg commented on oc_client_provider/tests/test_client_provider.py
> +        _expected_dict = list()
`dict` is `list`...

2024-05-14 06:09 UTC, vifrrg commented on oc_client_provider/tests/test_client_provider.py
> +                                              'country': 'Scotland',
real country in test data

2024-05-15 06:00 UTC, vifrrg approved these changes

2024-05-15 06:00 UTC, vifrrg commented on oc_client_provider/app/client_tf.py
> +        return ClientLanguage.objects.get(code='rus')
Please parametrize default language, shoul be English if not set.

2024-05-15 06:01 UTC, merged